language: node_js

node_js:
  - '0.10'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - secure: jSXhiLA8DfWrUYu/vVD8QWPMchBno11pPt9r0aX1U9juweUC6Pd0htlzCXw4nuC7DK9UbfT33dJB7bheBW0OJwEyEQqNKDrdPbrpTMmx0gkjgcff5k2SunQi9FKJVWDt6TqFLRklSf1zfC0lAWtmOaPyHHtfplnW2AMksFbfdhw=

before_script:
  - git config --global user.name "Travis-CI"
  - git config --global user.email "johnagan+travis@gmail.com"
  - REPO_URL=https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git

script:
  - git clone $REPO_URL dist
  - cd dist
  - git checkout gh-pages
  - echo "<br/><br/>" >> index.html
  - git commit -am "added space to index"

after_success:
  - test $TRAVIS_BRANCH == "master" &&
    test $TRAVIS_PULL_REQUEST == "false" &&
    git push $REPO_URL gh-pages
