language: node_js
node_js:
  - '0.10'

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
    - GH_REF: github.com/johnagan/ci-demo.git
    - secure: jSXhiLA8DfWrUYu/vVD8QWPMchBno11pPt9r0aX1U9juweUC6Pd0htlzCXw4nuC7DK9UbfT33dJB7bheBW0OJwEyEQqNKDrdPbrpTMmx0gkjgcff5k2SunQi9FKJVWDt6TqFLRklSf1zfC0lAWtmOaPyHHtfplnW2AMksFbfdhw=

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" &&
  - test $TRAVIS_BRANCH == "master" &&
  - git subtree push --prefix dist https://$GH_TOKEN@$GH_REF gh-pages
